export const collection_assets=[
    {
        "primary_asset_contracts": [
            {
                "address": "0x3fbe256f336a938291fa090b4dc498e4c0cb7a99",
                "asset_contract_type": "non-fungible",
                "created_date": "2022-01-24T15:26:50.223193",
                "name": "FakeMutantApeYachtClub",
                "nft_version": "3.0",
                "opensea_version": null,
                "owner": 4991138,
                "schema_name": "ERC721",
                "symbol": "FMAYC",
                "total_supply": "0",
                "description": "--- PUBLIC MINTING AVAILABLE AT FAKEBOREDAPEYACHTCLUB.COM!!! ---\n\nVisit fakeboredapeyachtclub.com for more information!\n\nThe MUTANT APE YACHT CLUB is a collection of up to 20,000 Mutant Apes that can only be created by exposing an existing Bored Ape to a vial of MUTANT SERUM or by minting a Mutant Ape in the public sale.",
                "external_link": "https://www.fakeboredapeyachtclub.com/",
                "image_url": "https://lh3.googleusercontent.com/qAmdbPis1xE06a-qgGzU0KtQE1Awlel6wNl44YOhwtVJS_2BGeG4GO5EcNlEAwpvvlsuqJ3hQovrJoEWegV-oX_eq3Gas-SvgdzyMYw=s120",
                "default_to_fiat": false,
                "dev_buyer_fee_basis_points": 0,
                "dev_seller_fee_basis_points": 0,
                "only_proxied_transfers": false,
                "opensea_buyer_fee_basis_points": 0,
                "opensea_seller_fee_basis_points": 250,
                "buyer_fee_basis_points": 0,
                "seller_fee_basis_points": 250,
                "payout_address": "0xe83c82b9da886175f04fc24368510c4982e04c35"
            }
        ],
        "traits": {},
        "stats": {
            "one_day_volume": 0,
            "one_day_change": -1,
            "one_day_sales": 0,
            "one_day_average_price": 0,
            "seven_day_volume": 320.7,
            "seven_day_change": 0,
            "seven_day_sales": 7,
            "seven_day_average_price": 45.81428571428571,
            "thirty_day_volume": 320.7,
            "thirty_day_change": 0,
            "thirty_day_sales": 7,
            "thirty_day_average_price": 45.81428571428571,
            "total_volume": 320.7,
            "total_sales": 7,
            "total_supply": 24,
            "count": 24,
            "num_owners": 13,
            "average_price": 45.81428571428571,
            "num_reports": 0,
            "market_cap": 1099.5428571428572,
            "floor_price": 0
        },
        "banner_image_url": "https://lh3.googleusercontent.com/ME2kXjgD-VNV2QW39xHUB9MX5naKFM5iZul4tFJU080Tlj8JJ1xbdEg-1DG-F0YFC2AkJcktHPwYh8JyxzFA7PUi22RE3UDO6oDd4w=s2500",
        "chat_url": null,
        "created_date": "2022-01-24T15:34:04.280359",
        "default_to_fiat": false,
        "description": "--- PUBLIC MINTING AVAILABLE AT FAKEBOREDAPEYACHTCLUB.COM!!! ---\n\nVisit fakeboredapeyachtclub.com for more information!\n\nThe MUTANT APE YACHT CLUB is a collection of up to 20,000 Mutant Apes that can only be created by exposing an existing Bored Ape to a vial of MUTANT SERUM or by minting a Mutant Ape in the public sale.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
            "card_display_style": "contain"
        },
        "external_url": "https://www.fakeboredapeyachtclub.com/",
        "featured": false,
        "featured_image_url": null,
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://lh3.googleusercontent.com/qAmdbPis1xE06a-qgGzU0KtQE1Awlel6wNl44YOhwtVJS_2BGeG4GO5EcNlEAwpvvlsuqJ3hQovrJoEWegV-oX_eq3Gas-SvgdzyMYw=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": null,
        "medium_username": null,
        "name": "Fake Mutant Ape Yacht Club",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": "0xe83c82b9da886175f04fc24368510c4982e04c35",
        "require_email": false,
        "short_description": null,
        "slug": "fake-mutant-ape-yacht-club",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "owned_asset_count": 4
    },
    {
        "primary_asset_contracts": [
            {
                "address": "0x79798affeffeeca38e7f5a2529e808ccfc11dcc3",
                "asset_contract_type": "semi-fungible",
                "created_date": "2022-01-24T09:29:59.464060",
                "name": "Unidentified contract",
                "nft_version": null,
                "opensea_version": null,
                "owner": 4991138,
                "schema_name": "ERC1155",
                "symbol": "",
                "total_supply": null,
                "description": "--- Available soon! ---\n\nWill be able to claim on fakeboredapeyachtclub.com for everyone who owns a fake bored ape (serums can only be claimed once and ape id will be marked once serum has been claimed)\nVisit fakeboredapeyachtclub.com for more information!",
                "external_link": "https://www.fakeboredapeyachtclub.com/",
                "image_url": "https://lh3.googleusercontent.com/4MuC9oOGY_kDrNLO98td94201YIKkYu6hA7b9QXP0tfpNUVKKEPUVQY9sElBg7XKt0nbiuw7UW4M1DO28wBNIyuRIE904DpbnKNSiQ=s120",
                "default_to_fiat": false,
                "dev_buyer_fee_basis_points": 0,
                "dev_seller_fee_basis_points": 0,
                "only_proxied_transfers": false,
                "opensea_buyer_fee_basis_points": 0,
                "opensea_seller_fee_basis_points": 250,
                "buyer_fee_basis_points": 0,
                "seller_fee_basis_points": 250,
                "payout_address": "0xe83c82b9da886175f04fc24368510c4982e04c35"
            }
        ],
        "traits": {},
        "stats": {
            "one_day_volume": 0,
            "one_day_change": 0,
            "one_day_sales": 0,
            "one_day_average_price": 0,
            "seven_day_volume": 0,
            "seven_day_change": 0,
            "seven_day_sales": 0,
            "seven_day_average_price": 0,
            "thirty_day_volume": 0,
            "thirty_day_change": 0,
            "thirty_day_sales": 0,
            "thirty_day_average_price": 0,
            "total_volume": 0,
            "total_sales": 0,
            "total_supply": 3,
            "count": 3,
            "num_owners": 1,
            "average_price": 0,
            "num_reports": 0,
            "market_cap": 0,
            "floor_price": 0
        },
        "banner_image_url": "https://lh3.googleusercontent.com/ipRIyq_iETkqALn2Hpgdr41lWZVXMelffM6GVvW8xTkIlwyGAwZfCpcdn3taDrgbzh8QI-sycwo9OJIIzzGpRBzIwase8bxyZQkF=s2500",
        "chat_url": null,
        "created_date": "2022-01-24T09:55:17.434473",
        "default_to_fiat": false,
        "description": "--- Available soon! ---\n\nWill be able to claim on fakeboredapeyachtclub.com for everyone who owns a fake bored ape (serums can only be claimed once and ape id will be marked once serum has been claimed)\nVisit fakeboredapeyachtclub.com for more information!",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
            "card_display_style": "contain"
        },
        "external_url": "https://www.fakeboredapeyachtclub.com/",
        "featured": false,
        "featured_image_url": null,
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://lh3.googleusercontent.com/4MuC9oOGY_kDrNLO98td94201YIKkYu6hA7b9QXP0tfpNUVKKEPUVQY9sElBg7XKt0nbiuw7UW4M1DO28wBNIyuRIE904DpbnKNSiQ=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": null,
        "medium_username": null,
        "name": "Fake Bored Ape Chemistry Club",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": "0xe83c82b9da886175f04fc24368510c4982e04c35",
        "require_email": false,
        "short_description": null,
        "slug": "fake-bored-ape-chemistry-club",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "owned_asset_count": 10000
    },
    {
        "primary_asset_contracts": [
            {
                "address": "0x7470ea065e50e3862cd9b8fb7c77712165da80e5",
                "asset_contract_type": "non-fungible",
                "created_date": "2022-01-06T01:57:37.754171",
                "name": "FakeBoredApeYachtClub",
                "nft_version": "3.0",
                "opensea_version": null,
                "owner": 4991138,
                "schema_name": "ERC721",
                "symbol": "FBAYC",
                "total_supply": "10",
                "description": "--- PUBLIC MINTING NOW AVAILABLE ON FAKEBOREDAPEYACHTCLUB.COM!!! ---\n\nThe Bored Ape Yacht Club is a collection of 10,000 unique Bored Ape NFTs— unique digital collectibles living on the Ethereum blockchain. Your Bored Ape means nothing since this is only on the testnet but its fun to have anyway. Visit www.FakeBoredApeYachtClub.com for more details about the project.",
                "external_link": "https://www.fakeboredapeyachtclub.com/",
                "image_url": "https://lh3.googleusercontent.com/Fbv0Mbut8q_MRfMB-F2stO9PzPd3zSiy0HQu-PJQszorWGU0m0QzQWUSaHt91ndBFxaWx0aTP8Pp-5-tHIrxe1dl5IASTYLRTSzx=s120",
                "default_to_fiat": false,
                "dev_buyer_fee_basis_points": 0,
                "dev_seller_fee_basis_points": 0,
                "only_proxied_transfers": false,
                "opensea_buyer_fee_basis_points": 0,
                "opensea_seller_fee_basis_points": 250,
                "buyer_fee_basis_points": 0,
                "seller_fee_basis_points": 250,
                "payout_address": "0xe83c82b9da886175f04fc24368510c4982e04c35"
            }
        ],
        "traits": {},
        "stats": {
            "one_day_volume": 30,
            "one_day_change": 0,
            "one_day_sales": 2,
            "one_day_average_price": 15,
            "seven_day_volume": 186,
            "seven_day_change": 2.0491803278688523,
            "seven_day_sales": 8,
            "seven_day_average_price": 23.25,
            "thirty_day_volume": 652.656,
            "thirty_day_change": 12.001115537848603,
            "thirty_day_sales": 33,
            "thirty_day_average_price": 19.777454545454543,
            "total_volume": 702.856,
            "total_sales": 40,
            "total_supply": 777,
            "count": 777,
            "num_owners": 103,
            "average_price": 17.5714,
            "num_reports": 0,
            "market_cap": 18065.25,
            "floor_price": 0
        },
        "banner_image_url": "https://lh3.googleusercontent.com/iux3DtSFXIEtbdw89TDlvbc65GcUcZ0WFipZ_lW93GsZDkkGKQy1SYMZqXiI_Ngcmdn_kgEI6A4R8T-ptXQpEMU2NzAecZHAEs2rWw=s2500",
        "chat_url": null,
        "created_date": "2022-01-06T01:57:38.071659",
        "default_to_fiat": false,
        "description": "--- PUBLIC MINTING NOW AVAILABLE ON FAKEBOREDAPEYACHTCLUB.COM!!! ---\n\nThe Bored Ape Yacht Club is a collection of 10,000 unique Bored Ape NFTs— unique digital collectibles living on the Ethereum blockchain. Your Bored Ape means nothing since this is only on the testnet but its fun to have anyway. Visit www.FakeBoredApeYachtClub.com for more details about the project.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
            "card_display_style": "contain"
        },
        "external_url": "https://www.fakeboredapeyachtclub.com/",
        "featured": false,
        "featured_image_url": null,
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://lh3.googleusercontent.com/Fbv0Mbut8q_MRfMB-F2stO9PzPd3zSiy0HQu-PJQszorWGU0m0QzQWUSaHt91ndBFxaWx0aTP8Pp-5-tHIrxe1dl5IASTYLRTSzx=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": null,
        "medium_username": null,
        "name": "Fake Bored Ape Yacht Club",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": "0xe83c82b9da886175f04fc24368510c4982e04c35",
        "require_email": false,
        "short_description": null,
        "slug": "fakeboredapeyachtclub",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "owned_asset_count": 62
    }
];